const data = [
    //https://api.github.com/users/sallygoshadze
    {
        login: "sallygoshadze",
        id: 74931153,
        node_id: "MDQ6VXNlcjc0OTMxMTUz",
        avatar_url: "https://avatars3.githubusercontent.com/u/74931153?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/sallygoshadze",
        html_url: "https://github.com/sallygoshadze",
        followers_url: "https://api.github.com/users/sallygoshadze/followers",
        following_url: "https://api.github.com/users/sallygoshadze/following{/other_user}",
        gists_url: "https://api.github.com/users/sallygoshadze/gists{/gist_id}",
        starred_url: "https://api.github.com/users/sallygoshadze/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/sallygoshadze/subscriptions",
        organizations_url: "https://api.github.com/users/sallygoshadze/orgs",
        repos_url: "https://api.github.com/users/sallygoshadze/repos",
        events_url: "https://api.github.com/users/sallygoshadze/events{/privacy}",
        received_events_url: "https://api.github.com/users/sallygoshadze/received_events",
        type: "User",
        site_admin: false,
        name: "Salome Goshadze",
        company: null,
        blog: "",
        location: null,
        email: null,
        hireable: null,
        bio: null,
        twitter_username: null,
        public_repos: 30,
        public_gists: 0,
        followers: 1,
        following: 2,
        created_at: "2020-11-23T19:39:26Z",
        updated_at: "2021-01-01T14:23:35Z"
    },
    {
        login: "joffarex",
        id: 41587092,
        node_id: "MDQ6VXNlcjQxNTg3MDky",
        avatar_url: "https://avatars2.githubusercontent.com/u/41587092?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/joffarex",
        html_url: "https://github.com/joffarex",
        followers_url: "https://api.github.com/users/joffarex/followers",
        following_url: "https://api.github.com/users/joffarex/following{/other_user}",
        gists_url: "https://api.github.com/users/joffarex/gists{/gist_id}",
        starred_url: "https://api.github.com/users/joffarex/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/joffarex/subscriptions",
        organizations_url: "https://api.github.com/users/joffarex/orgs",
        repos_url: "https://api.github.com/users/joffarex/repos",
        events_url: "https://api.github.com/users/joffarex/events{/privacy}",
        received_events_url: "https://api.github.com/users/joffarex/received_events",
        type: "User",
        site_admin: false,
        name: "Tornike Goshadze",
        company: null,
        blog: "",
        location: "Tbilisi, Georgia",
        email: null,
        hireable: null,
        bio: "I love when I make stuff appear on the computer screen. ",
        twitter_username: null,
        public_repos: 20,
        public_gists: 2,
        followers: 7,
        following: 23,
        created_at: "2018-07-23T15:59:40Z",
        updated_at: "2021-01-01T21:55:26Z"
    },
    {
        login: "sallygoshadze",
        id: 74931153,
        node_id: "MDQ6VXNlcjc0OTMxMTUz",
        avatar_url: "https://avatars3.githubusercontent.com/u/74931153?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/sallygoshadze",
        html_url: "https://github.com/sallygoshadze",
        followers_url: "https://api.github.com/users/sallygoshadze/followers",
        following_url: "https://api.github.com/users/sallygoshadze/following{/other_user}",
        gists_url: "https://api.github.com/users/sallygoshadze/gists{/gist_id}",
        starred_url: "https://api.github.com/users/sallygoshadze/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/sallygoshadze/subscriptions",
        organizations_url: "https://api.github.com/users/sallygoshadze/orgs",
        repos_url: "https://api.github.com/users/sallygoshadze/repos",
        events_url: "https://api.github.com/users/sallygoshadze/events{/privacy}",
        received_events_url: "https://api.github.com/users/sallygoshadze/received_events",
        type: "User",
        site_admin: false,
        name: "Salome Goshadze",
        company: null,
        blog: "",
        location: null,
        email: null,
        hireable: null,
        bio: null,
        twitter_username: null,
        public_repos: 30,
        public_gists: 0,
        followers: 1,
        following: 2,
        created_at: "2020-11-23T19:39:26Z",
        updated_at: "2021-01-01T14:23:35Z"
    }
]

export default data;